name: Release

on:
  release:
    types: [created]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "20.10"
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test

  build:
    needs: [test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "20.10"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  check-exports:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "20.10"
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Check exports
        run: npm run check-exports

  publish:
    needs: [check-exports]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          cache: "npm"
          node-version: "20.10"
      - uses: actions/download-artifact@v4
        with:
          name: dist
      - name: Install dependencies
        run: npm ci
      - name: Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          publish: npm run release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
